import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import Providers from "@/utils/Providers";
import { cn } from "@/lib/utils";
import Navigation from "@/components/store/navigation/Navigation";
import Footer from "@/components/store/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "overflow-x-hidden min-h-screen flex flex-col "
        )}
      >
        {/* <Providers> */}
        <Navigation />
        <div className="flex-1">{children}</div>
        <Footer />
        {/* </Providers> */}
      </body>
    </html>
  );
}
